"""Generate sample/brdf/skintone_callisto_brdf.brdf, derived from sample/brdf/callisto_brdf.brdf.

The shader is copied from callisto_brdf.brdf; only the base colour differs. It is built
from a skin tone chart (110 columns), an LDR mask and a hair mask, following a UE
material graph:

    tone  = chart(column floor(skintone + 0.1), centre row)       # chart values, not decoded
    skin  = pow(saturate(ldr_mask - 0.5 + tone), 2.2)              # gamma 2.2 -> linear
    albedo = lerp(skin, sRGB_decode(base_color), hair_mask)

The chart is not a texture of the .brdf: its 110 column samples are embedded as a
constant array (SKIN_CHART). Each value is what a bilinear, unmipped, wrap-addressed
fetch of the 8-bit chart returns at u = (i - 0.5) / 110, v = 0.5.

    python scripts/gen_skintone_callisto.py [--chart PATH_TO_CHART.png]

Without --chart, the array already in the generated file is kept (the chart image is
not part of the repository). Re-run after editing callisto_brdf.brdf.
"""
from __future__ import annotations

import argparse
import math
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
BASE = os.path.join(ROOT, "sample", "brdf", "callisto_brdf.brdf")
NAME = "skintone_callisto_brdf"
OUT = os.path.join(ROOT, "sample", "brdf", NAME + ".brdf")
COLUMNS = 110

BASE_COLOR_LINE = (
    "color base_color 0.72 0.53 0.45  # 髪の部分の色（sRGB）。hair_mask が 1 の所で使う。Lit Object の dm.obj では "
    "T_emily_BC が既定で付く / colour of the hair area (sRGB), used where hair_mask is 1; "
    "T_emily_BC by default on the Lit Object dm.obj"
)
NEW_PARAMS = [
    "float skintone 1.0 110.0 72.0  # 肌トーンの番号（チャートの列 1〜110、小数は切り捨て）。hair_mask が 0 の所の色を決める / "
    "skin tone number (chart column 1-110, fraction dropped); sets the colour where hair_mask is 0",
    "color ldr_mask 0.5 0.5 0.5  # 肌の明暗の差分。0.5 が基準で、チャートの色に (値−0.5) を足す。テクスチャは値をそのまま使う"
    "（sRGB 扱い、デコードなし）。dm.obj では Test_face_system_LDR_MASK が既定で付く / skin shading offset: "
    "(value - 0.5) is added to the chart colour, 0.5 = none; a texture is used as is (sRGB, not decoded); "
    "Test_face_system_LDR_MASK by default on dm.obj",
    "float hair_mask 0.0 1.0 0.0  # 髪マスク（R）。0 で肌トーン、1 で base_color / hair mask (R): 0 = skin tone, "
    "1 = base_color; Test_face_system_HairMask by default on dm.obj",
]

# defaults that differ from callisto_brdf.brdf (float parameters)
DEFAULTS = {"roughness1_scale": 1.1}

ALBEDO_OLD = """vec3 BRDF_sss_albedo() {
    return saturate(mon2lin(base_color));
}
"""


def srgb8(x: int) -> float:
    return x / 255.0


def sample_chart(path: str) -> list[tuple[float, float, float]]:
    from PIL import Image

    img = Image.open(path).convert("RGB")
    w, h = img.size
    px = img.load()

    def texel(x: int, y: int) -> tuple[float, ...]:
        return tuple(srgb8(c) for c in px[x % w, y % h])  # TA_Wrap

    def bilinear(u: float, v: float) -> tuple[float, ...]:
        x, y = u * w - 0.5, v * h - 0.5
        x0, y0 = math.floor(x), math.floor(y)
        fx, fy = x - x0, y - y0
        c00, c10, c01, c11 = texel(x0, y0), texel(x0 + 1, y0), texel(x0, y0 + 1), texel(x0 + 1, y0 + 1)
        return tuple(
            (a * (1 - fx) + b * fx) * (1 - fy) + (c * (1 - fx) + d * fx) * fy for a, b, c, d in zip(c00, c10, c01, c11)
        )

    cell = 1.0 / COLUMNS
    return [bilinear(i * cell - cell * 0.5, 0.5) for i in range(1, COLUMNS + 1)]


def read_existing_chart() -> list[tuple[float, float, float]]:
    if not os.path.exists(OUT):
        raise SystemExit(f"{OUT} does not exist yet: pass --chart PATH_TO_CHART.png")
    text = open(OUT, encoding="utf-8").read()
    m = re.search(r"const vec3 SKIN_CHART\[110\] = vec3\[110\]\((.*?)\);", text, re.S)
    if not m:
        raise SystemExit("SKIN_CHART not found in the existing file: pass --chart")
    vals = [tuple(float(x) for x in v.split(",")) for v in re.findall(r"vec3\(([^)]*)\)", m.group(1))]
    if len(vals) != COLUMNS:
        raise SystemExit(f"SKIN_CHART has {len(vals)} entries, expected {COLUMNS}")
    return vals


def chart_glsl(chart: list[tuple[float, float, float]]) -> str:
    rows = [f"    vec3({r:.6f}, {g:.6f}, {b:.6f})" for r, g, b in chart]
    return f"const vec3 SKIN_CHART[110] = vec3[110](\n" + ",\n".join(rows) + "\n);\n"


def albedo_glsl(chart: list[tuple[float, float, float]]) -> str:
    return (
        "// ---- skin tone base colour (this file only) ----\n"
        "// Chart column samples (u = (i - 0.5) / 110, v = 0.5), not decoded: the chart is read as\n"
        "// gamma-space values. Generated by scripts/gen_skintone_callisto.py.\n"
        + chart_glsl(chart)
        + """
// Linear albedo: skin tone from the chart plus the LDR mask offset, raised to 2.2
// (not the exact sRGB curve), blended with the decoded base_color by hair_mask.
vec3 skinToneAlbedo() {
    int column = int(clamp(floor(skintone + 0.1), 1.0, 110.0) - 1.0);
    vec3 skin = saturate((ldr_mask - vec3(0.5)) + SKIN_CHART[column]);
    skin = pow(max(skin, vec3(0.0)), vec3(2.2));
    return mix(skin, mon2lin(base_color), saturate(hair_mask));
}

vec3 BRDF_sss_albedo() {
    return saturate(skinToneAlbedo());
}
"""
    )


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--chart", help="skin tone chart image (110 columns side by side)")
    args = ap.parse_args()
    chart = sample_chart(args.chart) if args.chart else read_existing_chart()

    src = open(BASE, "rb").read().decode("utf-8").replace("\r\n", "\n")
    head, rest = src.split("::begin parameters\n", 1)
    params, tail = rest.split("::end parameters\n", 1)

    out_params = []
    for line in params.splitlines():
        t = line.split("#")[0].split()
        if t and t[1] == "base_color":
            out_params += [BASE_COLOR_LINE, *NEW_PARAMS]
        elif t and t[1] in DEFAULTS:
            decl, _, comment = line.partition("#")
            out_params.append(f"float {t[1]} {t[2]} {t[3]} {DEFAULTS[t[1]]:g}  # {comment.strip()}")
        else:
            out_params.append(line)
    if len(out_params) != len(params.splitlines()) + len(NEW_PARAMS):
        raise SystemExit("base_color parameter not found in callisto_brdf.brdf")
    if tail.count(ALBEDO_OLD) != 1:
        raise SystemExit("BRDF_sss_albedo() of callisto_brdf.brdf changed; update ALBEDO_OLD")
    tail = tail.replace(ALBEDO_OLD, albedo_glsl(chart))
    for name in DEFAULTS:
        if not any(line.split("#")[0].split()[1:2] == [name] for line in out_params):
            raise SystemExit(f"{name} not found in callisto_brdf.brdf")

    header = (
        "analytic\n\n"
        "# DERIVED from callisto_brdf.brdf - skin tone base colour variant.\n"
        "# Generated by scripts/gen_skintone_callisto.py; do not edit by hand.\n"
        "# CUSTOM IMPLEMENTATION (独自実装). The lighting is identical to callisto_brdf.brdf;\n"
        "# only the albedo differs: it is built from a 110-column skin tone chart (embedded\n"
        "# as SKIN_CHART, selected by \"skintone\"), the LDR mask offset (ldr_mask - 0.5, added\n"
        "# in gamma space, then pow 2.2) and blended with base_color by hair_mask.\n"
        "# On the Lit Object mesh dm.obj, base_color, ldr_mask and hair_mask get default\n"
        "# textures (assets/obj/textures.json). Elsewhere the slider values are used.\n"
        "# Parameters below base_color follow callisto_brdf.brdf, except roughness1_scale 1.1.\n"
        "#\n"
    )
    body = re.sub(r"^analytic\n\n", "", head)
    text = header + body + "::begin parameters\n" + "\n".join(out_params) + "\n::end parameters\n" + tail
    for d in ("sample/brdf", "web/public/brdfs"):
        path = os.path.join(ROOT, d, NAME + ".brdf")
        open(path, "wb").write(text.replace("\n", "\r\n").encode("utf-8"))
    print("wrote", NAME)


if __name__ == "__main__":
    main()
