"""Verify sample/brdf/skintone_callisto_brdf.brdf (generated by scripts/gen_skintone_callisto.py).

Two checks through brdf_view's own automation (capture.mjs --batch, evaluate in float32):

1. Albedo: BRDF_sss_albedo() for several skintone / ldr_mask / hair_mask / base_color values
   against a Python reference that reads the chart image itself (bilinear, wrap, v = 0.5):
       saturate(lerp(pow(saturate(ldr_mask - 0.5 + chart(u)), 2.2), sRGB_decode(base_color), hair_mask))
       u = (floor(skintone + 0.1) - 0.5) / 110
2. Lighting: with hair_mask = 1 the BRDF equals callisto_brdf.brdf with the same parameters
   (set explicitly: the defaults differ in roughness1_scale).

    python scripts/verify_skintone_brdf.py --chart PATH_TO_CHART.png [--out-dir DIR] [--skip-gpu]

Writes the batch file and the evaluate results to --out-dir (default verify_out/skintone/,
git-ignored).
"""
from __future__ import annotations

import argparse
import json
import math
import os
import subprocess

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

ALBEDO_CASES = [
    # skintone, ldr_mask, hair_mask, base_color (sRGB)
    (72.0, (0.5, 0.5, 0.5), 0.0, (0.72, 0.53, 0.45)),
    (1.0, (0.5, 0.5, 0.5), 0.0, (0.72, 0.53, 0.45)),
    (110.0, (0.5, 0.5, 0.5), 0.0, (0.72, 0.53, 0.45)),
    (1.95, (0.5, 0.5, 0.5), 0.0, (0.72, 0.53, 0.45)),   # floor(2.05) = 2
    (36.89, (0.5, 0.5, 0.5), 0.0, (0.72, 0.53, 0.45)),  # floor(36.99) = 36
    (55.0, (0.3, 0.6, 0.45), 0.0, (0.72, 0.53, 0.45)),
    (90.0, (1.0, 1.0, 1.0), 0.0, (0.72, 0.53, 0.45)),   # saturate clips
    (20.0, (0.0, 0.0, 0.0), 0.0, (0.72, 0.53, 0.45)),
    (72.0, (0.5, 0.5, 0.5), 1.0, (0.2, 0.1, 0.05)),
    (72.0, (0.62, 0.4, 0.5), 0.35, (0.2, 0.1, 0.05)),
]
DIRS = [{"thetaL": tl, "phiL": ph, "thetaV": tv, "phiV": 0} for tl in (0, 30, 70) for tv in (0, 45, 80) for ph in (0, 90, 180)]
LIGHTING_PARAMS = {"hair_mask": 1.0, "roughness1_scale": 1.1, "base_color": [0.6, 0.4, 0.3], "roughness": 0.4, "specular": 0.5}


def chart_reference(path: str):
    from PIL import Image

    img = Image.open(path).convert("RGB")
    w, h = img.size
    px = img.load()

    def fetch(u: float, v: float):
        x, y = u * w - 0.5, v * h - 0.5
        x0, y0 = math.floor(x), math.floor(y)
        fx, fy = x - x0, y - y0
        out = []
        for k in range(3):
            t = lambda xx, yy: px[xx % w, yy % h][k] / 255.0
            top = t(x0, y0) * (1 - fx) + t(x0 + 1, y0) * fx
            bot = t(x0, y0 + 1) * (1 - fx) + t(x0 + 1, y0 + 1) * fx
            out.append(top * (1 - fy) + bot * fy)
        return out

    return fetch


def srgb_decode(c: float) -> float:
    c = min(max(c, 0.0), 1.0)
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def albedo_reference(fetch, skintone, ldr, hair, base):
    cell = 1.0 / 110.0
    u = math.floor(skintone + 0.1) * cell - cell * 0.5
    tone = fetch(u, 0.5)
    out = []
    for k in range(3):
        s = min(max(ldr[k] - 0.5 + tone[k], 0.0), 1.0)
        s = 0.0 if s <= 2.980233e-8 else s ** 2.2
        v = s + (srgb_decode(base[k]) - s) * hair
        out.append(min(max(v, 0.0), 1.0))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--chart", required=True, help="skin tone chart image used to generate the .brdf")
    ap.add_argument("--out-dir", default=os.path.join(ROOT, "verify_out", "skintone"))
    ap.add_argument("--skip-gpu", action="store_true", help="reuse the results already in --out-dir")
    a = ap.parse_args()
    out = os.path.abspath(a.out_dir)
    os.makedirs(out, exist_ok=True)

    jobs = []
    for i, (st, ldr, hair, base) in enumerate(ALBEDO_CASES):
        params = {"skintone": st, "ldr_mask": list(ldr), "hair_mask": hair, "base_color": list(base)}
        jobs.append({"brdf": "skintone_callisto_brdf.brdf", "evalOut": f"albedo_{i}.json",
                     "eval": {"samples": DIRS[:1], "params": params, "component": "sssAlbedo"}})
    for name in ("skintone_callisto_brdf", "callisto_brdf"):
        params = {k: v for k, v in LIGHTING_PARAMS.items() if name != "callisto_brdf" or k != "hair_mask"}
        jobs.append({"brdf": name + ".brdf", "evalOut": f"lighting_{name}.json",
                     "eval": {"samples": DIRS, "params": params, "component": "brdf"}})
    batch = os.path.join(out, "batch.json")
    json.dump({"jobs": jobs}, open(batch, "w", encoding="utf-8"), indent=1)
    if not a.skip_gpu:
        cmd = ["node", os.path.join(ROOT, "web", "scripts", "capture.mjs"), "--batch", batch]
        r = subprocess.run(cmd, cwd=os.path.join(ROOT, "web"), capture_output=True, text=True, encoding="utf-8")
        if r.returncode != 0:
            print(r.stdout[-2000:])
            print(r.stderr[-4000:])
            raise SystemExit(f"capture failed ({r.returncode})")

    fetch = chart_reference(a.chart)
    ok_all = True
    print("| skintone | ldr_mask | hair_mask | GPU | reference | max abs err |")
    print("| --- | --- | --- | --- | --- | --- |")
    for i, (st, ldr, hair, base) in enumerate(ALBEDO_CASES):
        gpu = json.load(open(os.path.join(out, f"albedo_{i}.json"), encoding="utf-8"))["rgb"][0]
        ref = albedo_reference(fetch, st, ldr, hair, base)
        err = max(abs(g - r) for g, r in zip(gpu, ref))
        ok_all &= err < 1e-5
        fmt = lambda v: "(" + ", ".join(f"{x:.5f}" for x in v) + ")"
        print(f"| {st:g} | {fmt(ldr)} | {hair:g} | {fmt(gpu)} | {fmt(ref)} | {err:.2e} |")

    s = json.load(open(os.path.join(out, "lighting_skintone_callisto_brdf.json"), encoding="utf-8"))["rgb"]
    c = json.load(open(os.path.join(out, "lighting_callisto_brdf.json"), encoding="utf-8"))["rgb"]
    err = max(abs(x - y) / max(abs(y), 1e-6) for p, q in zip(s, c) for x, y in zip(p, q))
    ok_all &= err < 1e-5
    print(f"\nlighting vs callisto_brdf (hair_mask = 1): max rel. err {err:.2e}")
    print("PASS" if ok_all else "FAIL")
    return 0 if ok_all else 1


if __name__ == "__main__":
    raise SystemExit(main())
